// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_ekran
void ui_ekran_screen_init(void);
extern lv_obj_t * ui_ekran;
extern lv_obj_t * ui_temperature;
extern lv_obj_t * ui_templabel;
extern lv_obj_t * ui_temperaturelogo;
extern lv_obj_t * ui_humidity;
extern lv_obj_t * ui_humidtylabel;
extern lv_obj_t * ui_humiditylogo;
extern lv_obj_t * ui_light;
extern lv_obj_t * ui_lightlogo;
extern lv_obj_t * ui_lightlabel;
void ui_event_colors(lv_event_t * e);
extern lv_obj_t * ui_colors;
void ui_event_alarmbutton(lv_event_t * e);
extern lv_obj_t * ui_alarmbutton;
void ui_event_ImgButton1(lv_event_t * e);
extern lv_obj_t * ui_ImgButton1;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_212523610);    // assets/temperature (2).png
LV_IMG_DECLARE(ui_img_5528042);    // assets/humidity (1).png
LV_IMG_DECLARE(ui_img_1895508086);    // assets/idea-bulb (1).png
LV_IMG_DECLARE(ui_img_bell_png);    // assets/bell.png
LV_IMG_DECLARE(ui_img_2137509695);    // assets/bell (2).png
LV_IMG_DECLARE(ui_img_781912046);    // assets/bell (1).png
LV_IMG_DECLARE(ui_img_synchronize_png);    // assets/synchronize.png
LV_IMG_DECLARE(ui_img_1760234689);    // assets/synchronize (1).png

// FONTS
LV_FONT_DECLARE(ui_font_Font1);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
