// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_ekran_screen_init(void)
{
    ui_ekran = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ekran, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_ekran, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temperature = lv_arc_create(ui_ekran);
    lv_obj_set_width(ui_temperature, 88);
    lv_obj_set_height(ui_temperature, 126);
    lv_obj_set_x(ui_temperature, -97);
    lv_obj_set_y(ui_temperature, -49);
    lv_obj_set_align(ui_temperature, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_temperature, LV_STATE_DISABLED);       /// States
    lv_arc_set_value(ui_temperature, 50);

    ui_templabel = lv_label_create(ui_temperature);
    lv_obj_set_width(ui_templabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_templabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_templabel, 1);
    lv_obj_set_y(ui_templabel, 47);
    lv_obj_set_align(ui_templabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_templabel, "17.0");
    lv_obj_set_style_text_font(ui_templabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temperaturelogo = lv_img_create(ui_temperature);
    lv_img_set_src(ui_temperaturelogo, &ui_img_212523610);
    lv_obj_set_width(ui_temperaturelogo, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_temperaturelogo, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_temperaturelogo, -1);
    lv_obj_set_y(ui_temperaturelogo, -19);
    lv_obj_set_align(ui_temperaturelogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_temperaturelogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_temperaturelogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_humidity = lv_arc_create(ui_ekran);
    lv_obj_set_width(ui_humidity, 88);
    lv_obj_set_height(ui_humidity, 126);
    lv_obj_set_x(ui_humidity, 5);
    lv_obj_set_y(ui_humidity, -49);
    lv_obj_set_align(ui_humidity, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_humidity, LV_STATE_DISABLED);       /// States
    lv_arc_set_value(ui_humidity, 50);

    ui_humidtylabel = lv_label_create(ui_humidity);
    lv_obj_set_width(ui_humidtylabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humidtylabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humidtylabel, 1);
    lv_obj_set_y(ui_humidtylabel, 48);
    lv_obj_set_align(ui_humidtylabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humidtylabel, "50.0");
    lv_obj_set_style_text_font(ui_humidtylabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humiditylogo = lv_img_create(ui_humidity);
    lv_img_set_src(ui_humiditylogo, &ui_img_5528042);
    lv_obj_set_width(ui_humiditylogo, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_humiditylogo, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_humiditylogo, -1);
    lv_obj_set_y(ui_humiditylogo, -19);
    lv_obj_set_align(ui_humiditylogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_humiditylogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_humiditylogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_light = lv_arc_create(ui_ekran);
    lv_obj_set_width(ui_light, 88);
    lv_obj_set_height(ui_light, 126);
    lv_obj_set_x(ui_light, 109);
    lv_obj_set_y(ui_light, -49);
    lv_obj_set_align(ui_light, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_light, LV_STATE_DISABLED);       /// States
    lv_arc_set_range(ui_light, 0, 1000);
    lv_arc_set_value(ui_light, 100);

    ui_lightlogo = lv_img_create(ui_light);
    lv_img_set_src(ui_lightlogo, &ui_img_1895508086);
    lv_obj_set_width(ui_lightlogo, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_lightlogo, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_lightlogo, -1);
    lv_obj_set_y(ui_lightlogo, -19);
    lv_obj_set_align(ui_lightlogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lightlogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_lightlogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lightlabel = lv_label_create(ui_light);
    lv_obj_set_width(ui_lightlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lightlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lightlabel, 0);
    lv_obj_set_y(ui_lightlabel, 49);
    lv_obj_set_align(ui_lightlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lightlabel, "500");
    lv_obj_set_style_text_font(ui_lightlabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_colors = lv_roller_create(ui_ekran);
    lv_roller_set_options(ui_colors, "RED\nGREEN\nBLUE", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_colors, 148);
    lv_obj_set_height(ui_colors, 67);
    lv_obj_set_x(ui_colors, -70);
    lv_obj_set_y(ui_colors, 66);
    lv_obj_set_align(ui_colors, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_colors, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_colors, lv_color_hex(0x1504C2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_colors, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_colors, 10, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_alarmbutton = lv_imgbtn_create(ui_ekran);
    lv_imgbtn_set_src(ui_alarmbutton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_bell_png, NULL);
    lv_imgbtn_set_src(ui_alarmbutton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_2137509695, NULL);
    lv_imgbtn_set_src(ui_alarmbutton, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_781912046, NULL);
    lv_obj_set_width(ui_alarmbutton, 64);
    lv_obj_set_height(ui_alarmbutton, 64);
    lv_obj_set_x(ui_alarmbutton, 42);
    lv_obj_set_y(ui_alarmbutton, 69);
    lv_obj_set_align(ui_alarmbutton, LV_ALIGN_CENTER);

    ui_ImgButton1 = lv_imgbtn_create(ui_ekran);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_synchronize_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1760234689, NULL);
    lv_obj_set_width(ui_ImgButton1, 64);
    lv_obj_set_height(ui_ImgButton1, 64);
    lv_obj_set_x(ui_ImgButton1, 118);
    lv_obj_set_y(ui_ImgButton1, 68);
    lv_obj_set_align(ui_ImgButton1, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_colors, ui_event_colors, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_alarmbutton, ui_event_alarmbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton1, ui_event_ImgButton1, LV_EVENT_ALL, NULL);

}
